### ISSUE TITLE
Datepicker doesn't open on Chrome

### ISSUE THREAD

**Issue by simoneb** [nearform/quantum#228]
The datepicker doesn't open on Chrome.

![Image](https://github.com/nearform/quantum/assets/20181/3673deba-3457-4e24-8083-4a5be0c3120e)

You can check it out at https://oss-contributions-bpcqknlgsq-nw.a.run.app/profile/simoneb

**Comment by swdilip** [comment]
`DatePicker` component doesn't exist. For a project that requires a `DatePicker` like component, it can be achieved through a combination of `PopOver` and `Calendar`.

The above example in OSS contributions wasn't using the aforementioned approach and thus this problem isn't due to issues in the quantum library.
