### ISSUE TITLE
[Component] - Popover

### ISSUE THREAD

**Issue by nickzafiropulos** [nearform/quantum#270]
Figma - https://www.figma.com/file/XFbhstkgQFz8ZefAU3w2p4/1.-Quantum-Design-System?type=design&node-id=360-11193&mode=design

Storybook - https://nearform.github.io/quantum/?path=/docs/components-popover--docs

1. Please remove the bullets from the lists in the default variants
2. There should be a variant `with icons` that includes icons in the list items
3. By default, there shouldn't be a heading on the popovers. The heading should be on a separate variant, as shown in the Figma file, called `with header`
4. On the `with header` variant, there should be the option to turn a sub heading on/off.
5. When implementing the `with header` variant - please double check the spacing and padding of the heading elements. Currently the heading that has been implemented is a little too small, and the text is not correctly aligned vertically. The text elements should also be left aligned.
6. The actions at the bottom of the popovers should be an optional property. There should also be a little more padding at the bottom - see designs. 
7. The items within the popover lists should be clickable links, with full states for default, hover, selected, focused and pressed.
8. There will need to be a `with checkbox group` vairant - but I see the checkbox group component hasn't yet been built, so this will need to come later.
9. The `With Close Button` variant doesn't exist in the Figma file, but it could be useful still. It just needs some tweaking to the padding and spacing. Please ensure there is 16px padding top, left, right and bottom of the popover, and that there is 32px spacing between the text and the button.

**Comment by andreaforni** [comment]
Hi @nickzafiropulos,
I see your Figma design proposes different types of popover content: default, with icons, with header, etc.
These types of content are implemented in the Storybook's stories, and I agree that they need to be updated to match the design. 

The only thing I want to point out is that from a technical point of view, the Popover's content area can be anything; we are not providing a "popover content list with icons" or a "popover content with checkbox group". We only provide a generic "popover content" component that can contain anything.

And this is what other libraries do, like [Material-UI](https://mui.com/material-ui/react-popover/#basic-popover). 

So, I'm going to fix the Storybook's stories, but I'm not going to implement specific popover content components.

I wanted to highlight that so we are on the same page.

/cc @marceloFerreira90

**Comment by marceloFerreira90** [comment]
I agree. 2 / 3 examples of different data/components should suffice. We just want to show that it is possible or easy to add a popover with content

**Comment by nickzafiropulos** [comment]
@andreaforni - Thanks for clarifying. That makes sense, totally. 
It's useful to have these component variants in Figma, so designers can qiuckly and consistently put common popover types into app designs, but I agree they don't all need to be implemented in Storybook.

**Comment by andreaforni** [comment]
Hi @nickzafiropulos,
regarding the 7th point:

> The items within the popover lists should be clickable links, with full states for default, hover, selected, focused and pressed.

I decided not to add real working links in Popover examples because that required styling from zero the links and adding noise to the documented examples. For this reason, I decided just to change the items mouse pointer to suggest that they might be actionable items (even though are not). 

I hope this is okay for you.


https://github.com/nearform/quantum/assets/1233582/56b204ca-985f-4693-a2db-7742d47034f1

**Comment by nickzafiropulos** [comment]
@andreaforni for the time being it's. ok, but if possible, once we have implemented https://github.com/orgs/nearform/projects/69/views/1?pane=issue&itemId=49172637

I would like popovers to use this that component for links in lists. I will update the Figma component to include this component today.

**Comment by andreaforni** [comment]
> @andreaforni for the time being it's. ok, but if possible, once we have implemented https://github.com/orgs/nearform/projects/69/views/1?pane=issue&itemId=49172637
> 
> I would like popovers to use this that component for links in lists. I will update the Figma component to include this component today.

Yeah, it makes sense. I'll pick the Link ticket as the next ticket and go back and update the popover.

**Comment by andreaforni** [comment]
After a call with @Filippoperl, we agreed to implement the following examples in Storybook:

## Default: no header or footer, content is not scrolling
The "actions" items are `Link` components, so they can accept icons.
![default](https://github.com/nearform/quantum/assets/1233582/ae6d9607-8218-417d-be41-2c2ec1a23f16)

## With header, footer and the scrolling content
The "actions" items are `Link` components, so they can accept icons. The "Sign out" action is a `Link` too, and it's an example of `Link` with icon.

![header footer and scrolling content](https://github.com/nearform/quantum/assets/1233582/b4ab3b34-fa23-4f01-acb3-78f325ecb78d)

## With checkboxes
This example uses the `Checkbox` components. We display them without the optional "hint text", but the developer can add it since it is a feature supported by the Checkboxes.

![checkbox](https://github.com/nearform/quantum/assets/1233582/98eeee49-fd12-4d0c-9bc4-aea6fa365fb3)

## With radio
This example uses the `Radio` and `RadioGroup` components. As for the previous example, we display them without the optional "hint text", but the developer can add it since it is a feature supported by the `Radio`.

![radio](https://github.com/nearform/quantum/assets/1233582/2fb876ba-06a9-4d89-942c-eb22e5b8a28b)
